### PR TITLE
Ported over the grid and the ruler, reorganized the update section a bit

### PR DESCRIPTION
**Pull request by ontrigger**

### CODE REVIEW

**Comment by Luffyyy** [comment]
Just gonna ask for some explanation for what it does specifically.

**Comment by ontrigger** [comment]
The grid is, well, a grid that activates when you hold any of the widgets arrows/axis. The ruler is a tool activated by ctrl+r by default that sets a start/end point on the cursors position and prints the length between those 2 points in the console. Oh and current_position() now returns grid-aligned cursor positions. This affects unit spawning

**Comment by Luffyyy** [comment]
Alright, I'll just implement the "self._use_surface_move" to be more a key holding thing, because it's really annoying to use that mode all the time.

**Comment by ontrigger** [comment]
oh I actually just wanted to do something like that too but I guess you beat me to it

**Pull request merged**
